Kasai
kasekiguchi/drone pull request #14
Opened 2021-08-17 09:31 UTC by kasai-1812033

・メイン文に害鳥の数，追跡用ドローンの数を追加
・害鳥放逐用のプログラムの追加
　・害鳥の目標座標の算出（畑への進行）
　・害鳥用のコントローラの追加
　・追跡ドローンの目標座標の算出（襲来する害鳥へ進行）
　・ドローン用のコントローラの追加
　・害鳥放逐用のプロットファイルの追加

2021-08-18 02:49 UTC, kasekiguchi requested changes
aviなどデータは基本的にpull requestに含めないようにしてください。
MODEL_CLASSの変更の理由がわかりません。
離散時間用のDrone_Modelを作ったのなら離散時間であることがわかる名前にしてください。
Pestbirds_model.mなどクラスファイル名のルールに従ってください。
drone_Model.mはなんのため？
get_model_nameのcase 文の末尾に コメントとして何のためのどういうモデル化という説明を記入してください。
sheep_Model ? 不要なファイルは含めないようにしてください。
pestbirds_linear_model記述とコメントがあっていないようです。適切なコメントを残すように修正してください。

全般的に最低限必要なものにまとめなおしてください。またコメントで中身がわかるように各ファイルに適切にコメントをつけましょう。
そのうえでpull requestしなおしてください。

2021-08-30 04:44 UTC, kasekiguchi commented
新しく作ったファイルと関数にはどういうものかわかるように以下の情報をコメントで追加してください．
ファイル：何をするためのファイルかの説明
関数：何をするための関数かの説明，引数が何で返り値が何かの説明

2021-09-02 05:05 UTC, kasai-1812033 commented
9月2日　ファイル説明とコメント追加，不要ファイルの削除（修正内容）
・関数ファイルの引数と返し値の説明追加
・不要なファイル削除
・プログラムの不要部分削除
・main文に記述していた不要部分削除

2021-09-24 05:14 UTC, kasekiguchi requested changes
関数の説明を書くときは関数自体の機能だけでなく引数の記号と出力の記号それぞれの意味も説明するように。

2021-09-24 05:14 UTC, kasekiguchi commented on plot/dataplot_agreement.m
> +function dataplot_agreement(logger,N)
関数の説明を加えてください。
特定の目的のための関数の場合は関数名でそれがわかるようにしてください。

2021-09-24 05:14 UTC, kasekiguchi commented on plot/dataplot_tracebirds.m
> +function dataplot_tracebirds(logger,N,Nb,fp)
関数の説明を加えてください。
特定の目的のための関数の場合は関数名でそれがわかるようにしてください。

2021-09-24 05:14 UTC, kasekiguchi commented on plot/fig_plot_state.m
> +function fig_plot_state(agent,fp,N,Nb)
関数の説明を加えてください。
特定の目的のための関数の場合は関数名でそれがわかるようにしてください。

2021-09-24 05:14 UTC, kasekiguchi commented on reference/CaseStudy/Make_heart_reference.m
> +            error = Make_reference(i,:) - agent(i).plant.state.p';
plantではなくestimatorにしましょう。
CaseStudyは別ブランチ切っているのでこのプルリクエストと関係ないものはプルリクエストに含めないように。

2021-09-24 05:14 UTC, kasekiguchi commented on reference/trace_birds_pestbirds_Dis.m
> +classdef trace_birds_pestbirds_Dis < REFERENCE_CLASS
クラスの説明を加えてください。

2021-09-24 05:14 UTC, kasekiguchi commented on reference/wheelchair_trace_birds_pestbirds_Dis.m
> +classdef wheelchair_trace_birds_pestbirds_Dis < REFERENCE_CLASS
wheelchair?
何のためのクラスですか？

2021-09-24 05:14 UTC, kasekiguchi commented on sample/Cov_calc_cov.m
> +function result = Cov_calc_cov(x,xd)
sampleフォルダに入れるべきファイルですか？

2021-09-24 05:14 UTC, kasekiguchi commented on sample/Cov_distance.m
> +function distance = Cov_distance(agent1,agent2,flag)
sapleに入れるべきファイルですか？

2021-09-24 05:14 UTC, kasekiguchi commented on sample/Model_Drone.m
> +function Model = Model_Drone(id,dt,type,initial,varargin)
tracebird用ならそうであることがわかるようにファイル名を付けてください。

2021-09-24 05:14 UTC, kasekiguchi commented on sample/Reference_agreement.m
> +function Reference = Reference_agreement(N)
分散アルゴリズムですか？

2021-09-24 05:14 UTC, kasekiguchi commented on sample/dog_input.m
> +function result = dog_input(agent,fp,P,other,Cog,xd,other_agent,num,Na)
関数の説明を加えてください。
特定の目的のための関数の場合は関数名でそれがわかるようにしてください。
sampleフォルダの名前つけルールに従ってください。

2021-09-24 05:14 UTC, kasekiguchi commented on sample/typical_Connector_Natnet_sim.m
> +function typical_Connector_Natnet_sim(N,dt,noise)
名前付けルールに従ってください。

2021-09-24 05:14 UTC, kasekiguchi commented on sample/typical_Estimator_Direct.m
> +function typical_Estimator_Direct(agent)
名前付けルールに従ってください。

2022-04-28 00:34 UTC, closed without merging