MuraiWork
kasekiguchi/drone pull request #7
Opened 2020-12-14 08:55 UTC by Mtakuto-git

作成したコントローラーなどを追加しました．
自分が作成したコントローラーの中でリファレンスを生成している状態のプログラムになります．
キー入力でHLとMPCのコントローラーの切り替えを行っています．
よろしくお願いします．

2020-12-15 02:34 UTC, kasekiguchi requested changes
変更ファイルが多すぎます．
最新版をpullして自分の変更以外はchangedとして残らないようにしてください．

2020-12-16 05:40 UTC, kasekiguchi requested changes

2020-12-16 05:40 UTC, kasekiguchi commented on controller/func_HL_MPCholizontal/dataplot.m
> +%% ���O����
関数化しましょう．

2020-12-16 05:40 UTC, kasekiguchi commented on controller/func_HL_MPCholizontal/calcreference.m
> +function [ref] = calcreference(h2,h3,Num,Pdata,dt)
こちらをリファレンスクラスにするのかな？

2020-12-16 05:40 UTC, kasekiguchi commented on controller/func_HL_MPCholizontal/autoEval.m
> +function [eval,deval] = autoEval(in1,in2,Qm,Qmf,Qt,Qtf,in7,Ws,Wr,in10,in11,BLD,in13)
他ファイルもそうですが，自動生成されるものはフォルダを掘ってそこに生成されるようにできませんか？
つまり設計や調整の段階で見なければいけないファイルを明確化したいです．

2020-12-16 05:40 UTC, kasekiguchi commented on controller/func_HL_MPCholizontal/SectionsSetting.m
> +Sections_point = [0,0;
この立ち位置がよくわかりません．
必要なら関数としましょう．
また環境を設定するものであればEnvクラスとすることも考えましょう．
Section関係全般そうかな？

2020-12-16 05:40 UTC, kasekiguchi commented on controller/func_HL_MPCholizontal/Linedistance.m
> +function [Dis] = Linedistance(x1,y1,Sectionpoint,Sectionnumber)
細かい関数は必要とするクラスのmethodに登録しましょう．

2020-12-16 05:40 UTC, kasekiguchi commented on controller/func_HL_MPCholizontal/ControllerSetting.m
> +%隊列飛行のコントローラの設定
これはsampleに登録するファイルの内容では？

2020-12-16 07:26 UTC, Mtakuto-git commented on main.m
> +%             arranged_pos = arranged_position([0,0],N,1,0);
arranged_posと並び方が違うのですが，arranged_posの中でどの並びにするか選択する形でよろしいですか？

2020-12-16 07:26 UTC, Mtakuto-git commented on main.m
> +
承知しました．

2020-12-16 08:24 UTC, kasekiguchi commented on main.m
> +%             arranged_pos = arranged_position([0,0],N,1,0);
そうですね．
arranged_posの引数増やすなどして対応してください．

2022-09-15 04:22 UTC, closed without merging